config-version: 1.4
#
# MESSAGE
# Use "%player%" to place the username in the message.
message : '&hey %小兄弟%，不要想著要炸私服器阿。'

# PERMISSION-NODE
# People without this permission will not be able to place/use TNT.
# It is recommended to keep it lower-case.
ignite-permission: 'notnt.ignite'
place-permission: 'notnt.place'
